version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    user: 1001:1001
    volumes:
      - /var/apps/home-automation/mosquitto/config:/mosquitto/config
      - /var/apps/home-automation/mosquitto/log:/mosquitto/log
      - /var/apps/home-automation/mosquitto/data:/mosquitto/data
    networks:
      - internal
    ports:
      - "1883:1883"
    deploy:
      replicas: 1
 
  tasprogw:
    image: node:18-alpine
    user: 1001:1001
    hostname: tasprogw
    volumes:
      - /var/apps/home-automation/tasprogw:/app
    networks:
      - monitoring
      - internal
    working_dir: /app
    command:
      - node
      - -r
      - ts-node/register
      - src
    deploy:
      replicas: 1
 
  gateway:
    image: joschi64/mqtt-prometheus-gateway:latest
    user: 1001:1001
    hostname: gateway
    networks:
      - monitoring
      - internal
      - kong-net
    volumes:
      - /var/apps/home-automation/config.yaml:/config.yaml
      - /var/apps/home-automation/.env:/app/.env
    command: ["npm", "start"]
    deploy:
      replicas: 1
     
networks:
  kong-net:
    external: true
  monitoring:
    external: true
  internal:
