version: '3.9'
services:
  db:
    image: postgres:13-alpine
    user: 1001:1001
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD_FILE: /run/secrets/wiki_postgres_password
      POSTGRES_USER: wikijs
    secrets:
      - wiki_postgres_password
    volumes:
      - /var/apps/wiki/postgres:/var/lib/postgresql/data
      - /var/apps/wiki/dump:/dump
    networks:
      - internal

  wiki:
    image: requarks/wiki:2
    user: 1001:1001
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS_FILE: /run/secrets/wiki_postgres_password
      DB_NAME: wiki
      # LOGLEVEL: debug
    secrets:
      - wiki_postgres_password
    volumes:
      - /var/apps/wiki/config.yml:/var/wiki/config.yml
      - /var/apps/wiki/repo:/var/wiki/repo
    networks:
      - internal
      - kong-net

networks:
  internal:
  kong-net:
    external: true
  
secrets:
   wiki_postgres_password:
     external: true
