version: '3.9'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD_FILE: /var/run/wiki_password
      POSTGRES_USER: wiki
    volumes:
      - /var/apps/wiki/postgres:/var/lib/postgresql/data
      - /var/apps/wiki/dump:/dump
    networks:
      - wiki-internal

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS_FILE: /var/run/wiki_password
      DB_NAME: wiki
      # LOGLEVEL: debug
    volumes:
      - /var/apps/wiki/config.yml:/var/wiki/config.yml
      - /var/apps/wiki/repo:/var/wiki/repo
    networks:
      - internal
      - kong-net

networks:
  internal:
  kong-net:
    external: true
  
